import React from 'react';
import Head from 'next/head';
import classes from './MainLayout.module.scss';

const MainLayout = ({ title, children }) => {
  return (
    <div className={classes.root_container}>
      <Head>
        <title>{title}</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  );
};

export default MainLayout;
